version: '2'
services:
  krakeninterview-app:
    image: krakeninterview
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://krakeninterview-postgresql:5432/krakeninterview
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  krakeninterview-postgresql:
    extends:
      file: postgresql.yml
      service: krakeninterview-postgresql
